services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      platform: linux/arm64  # Define a arquitetura como ARM64 para o Raspberry Pi
    container_name: app
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      APP_ENV: development
